### ISSUE TITLE
Uploading is broken

### ISSUE THREAD

**Issue by lauratorgeson** [drewtorg/wramtas#19]
Uploads only stay around for a few hours due to the nature of heroku. Switch all file uploads to use the file picker controls that interface with file stack. Add an uploads page for admins that allows you to view all uploaded documents. Because there could be many uploads on the site, consider a from of pagination.  Consider ways to allow non admin users to upload images in the tinymce text box.

**Comment by drewtorg** [comment]
Completed in 6b19410b83cf33ef2a6e5e66467035c2d82687d5
